# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "ahci" "ohci_pci" "ehci_pci" "pata_atiixp" "usbhid" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/d6aa480f-d002-4f23-a8ff-ea03b5d3b9a7";
      fsType = "btrfs";
    };


  swapDevices =
    [ { device = "/dev/disk/by-uuid/2c73b5c0-8a33-44ce-8cd3-e12097b164e4"; }
    ];

  nix.maxJobs = lib.mkDefault 6;
}
