{ ... } : 
''
; This file installs keyboard shortcuts from Photoshop 6 in GIMP 2.8.
;
; Rename it to 'menurc' and place it into your personal GIMP directory:
; ~/.gimp-2.8 folder (Linux) or C:\Documents and Settings\<user>\.gimp-2.8
; folder (Windows).
;
; There is a web-page describing these keybindings at
; http://epierce.freeshell.org/gimp/gimp_ps.php
;
(gtk_accel_path "<Actions>/view/view-shrink-wrap" "")
(gtk_accel_path "<Actions>/plug-in/plug_in_iwarp" "<Primary><Shift>x")
(gtk_accel_path "<Actions>/layers/layers-duplicate" "<Primary>j")
(gtk_accel_path "<Actions>/plug-in/plug_in_c_astretch" "<Primary><Shift><Alt>l")
(gtk_accel_path "<Actions>/context/context-brush-select-next" "period")
(gtk_accel_path "<Actions>/view/view-show-grid" "<Primary><Alt>apostrophe")
(gtk_accel_path "<Actions>/tools/tools-color-balance" "<Primary>b")
(gtk_accel_path "<Actions>/tools/tools-rotate" "")
(gtk_accel_path "<Actions>/image/image-rotate-270" "7")
(gtk_accel_path "<Actions>/layers/layers-mode-next" "plus")
(gtk_accel_path "<Actions>/dialogs/dialogs-brushes" "")
(gtk_accel_path "<Actions>/tools/tools-by-color-select" "<Primary><Shift>c")
(gtk_accel_path "<Actions>/tools/tools-vector" "p")
(gtk_accel_path "<Actions>/dialogs/dialogs-tool-options" "F5")
(gtk_accel_path "<Actions>/dialogs/dialogs-channels" "<Shift>F7")
(gtk_accel_path "<Actions>/qmask/qmask-toggle" "q")
(gtk_accel_path "<Actions>/tools/tools-value-2-increase" "")
(gtk_accel_path "<Actions>/layers/layers-alpha-selection-replace" "<Alt>a")
(gtk_accel_path "<Actions>/file/file-open-recent-10" "")
(gtk_accel_path "<Actions>/plug-in/plug_in_colortoalpha" "<Primary><Shift>a")
(gtk_accel_path "<Actions>/select/select-feather" "<Primary><Shift>d")
(gtk_accel_path "<Actions>/tools/tools-align" "")
(gtk_accel_path "<Actions>/layers/layers-select-top" "<Alt>braceright")
(gtk_accel_path "<Actions>/select/select-float" "")
(gtk_accel_path "<Actions>/tools/tools-desaturate" "<Primary><Shift>u")
(gtk_accel_path "<Actions>/select/select-invert" "<Primary><Shift>i")
(gtk_accel_path "<Actions>/plug-in/tiny_fu_refresh" "<Primary><Shift><Alt>t")
(gtk_accel_path "<Actions>/layers/layers-lower-to-bottom" "<Primary>braceleft")
(gtk_accel_path "<Actions>/layers/layers-lower" "<Primary>bracketleft")
(gtk_accel_path "<Actions>/image/image-convert-indexed" "backslash")
(gtk_accel_path "<Actions>/view/view-zoom-1-1" "<Primary><Alt>0")
(gtk_accel_path "<Actions>/view/view-scroll-page-left" "<Primary>Page_Up")
(gtk_accel_path "<Actions>/view/view-zoom-fit-to" "<Primary>0")
(gtk_accel_path "<Actions>/dialogs/dialogs-undo-history" "<Shift>F9")
(gtk_accel_path "<Actions>/layers/layers-resize-to-image" "<Alt>y")
(gtk_accel_path "<Actions>/plug-in/plug_in_gauss" "<Primary><Shift>b")
(gtk_accel_path "<Actions>/tools/tools-curves" "<Primary>m")
(gtk_accel_path "<Actions>/plug-in/plug_in_bump_map" "<Primary><Shift>m")
(gtk_accel_path "<Actions>/tools/tools-airbrush" "j")
(gtk_accel_path "<Actions>/image/image-flatten" "<Shift>i")
(gtk_accel_path "<Actions>/image/image-merge-layers" "<Primary><Shift>e")
(gtk_accel_path "<Actions>/view/view-scroll-page-right" "<Primary>Page_Down")
(gtk_accel_path "<Actions>/view/view-snap-to-guides" "<Primary>semicolon")
(gtk_accel_path "<Actions>/drawable/drawable-invert" "<Primary>i")
(gtk_accel_path "<Actions>/tools/tools-paint-brush-size-increase" "bracketright")
(gtk_accel_path "<Actions>/file/file-revert" "F12")
(gtk_accel_path "<Actions>/plug-in/plug-in-iwarp" "<Primary><Shift>x")
(gtk_accel_path "<Actions>/context/context-brush-select-previous" "comma")
(gtk_accel_path "<Actions>/tools/tools-convolve" "r")
(gtk_accel_path "<Actions>/file/file-export-to" "")
(gtk_accel_path "<Actions>/tools/tools-magnify" "z")
(gtk_accel_path "<Actions>/view/view-zoom-in" "<Primary>equal")
(gtk_accel_path "<Actions>/view/view-zoom-fit-in" "<Primary>0")
(gtk_accel_path "<Actions>/dialogs/dialogs-gradients" "<Primary><Shift>g")
(gtk_accel_path "<Actions>/image/image-duplicate" "")
(gtk_accel_path "<Actions>/edit/edit-clear" "")
(gtk_accel_path "<Actions>/edit/edit-fill-fg" "<Alt>BackSpace")
(gtk_accel_path "<Actions>/tools/tools-crop" "c")
(gtk_accel_path "<Actions>/edit/edit-redo" "<Primary><Shift>z")
(gtk_accel_path "<Actions>/select/select-none" "<Primary>d")
(gtk_accel_path "<Actions>/context/context-brush-select-last" "greater")
(gtk_accel_path "<Actions>/layers/layers-raise" "<Primary>bracketright")
(gtk_accel_path "<Actions>/image/image-properties" "F8")
(gtk_accel_path "<Actions>/tools/tools-levels" "<Primary>l")
(gtk_accel_path "<Actions>/dialogs/dialogs-document-history" "<Primary><Shift>h")
(gtk_accel_path "<Actions>/tools/tools-eraser" "e")
(gtk_accel_path "<Actions>/view/view-show-guides" "<Primary>apostrophe")
(gtk_accel_path "<Actions>/file/file-export" "")
(gtk_accel_path "<Actions>/edit/edit-fill-bg" "<Primary>BackSpace")
(gtk_accel_path "<Actions>/dialogs/dialogs-colors" "F6")
(gtk_accel_path "<Actions>/image/image-print-size" "<Primary>p")
(gtk_accel_path "<Actions>/context/context-brush-select-first" "less")
(gtk_accel_path "<Actions>/tools/tools-blend" "g")
(gtk_accel_path "<Actions>/file/file-save-a-copy" "<Primary><Alt>s")
(gtk_accel_path "<Actions>/image/image-rotate-180" "8")
(gtk_accel_path "<Actions>/tools/tools-clone" "s")
(gtk_accel_path "<Actions>/context/context-brush-hardness-increase-skip" "braceright")
(gtk_accel_path "<Actions>/dialogs/dialogs-layers" "F7")
(gtk_accel_path "<Actions>/view/view-scroll-page-up" "Page_Up")
(gtk_accel_path "<Actions>/plug-in/file_print_gimp" "<Primary>p")
(gtk_accel_path "<Actions>/layers/layers-merge-down" "<Primary>e")
(gtk_accel_path "<Actions>/tools/tools-rect-select" "m")
(gtk_accel_path "<Actions>/view/view-scroll-page-down" "Page_Down")
(gtk_accel_path "<Actions>/tools/tools-bucket-fill" "<Shift>g")
(gtk_accel_path "<Actions>/image/image-rotate-90" "9")
(gtk_accel_path "<Actions>/layers/layers-mode-previous" "underscore")
(gtk_accel_path "<Actions>/layers/layers-preserve-transparency" "slash")
(gtk_accel_path "<Actions>/tools/tools-measure" "u")
(gtk_accel_path "<Actions>/tools/tools-cage" "")
(gtk_accel_path "<Actions>/tools/tools-paintbrush" "b")
(gtk_accel_path "<Actions>/tools/tools-dodge-burn" "o")
(gtk_accel_path "<Actions>/tools/tools-color-picker" "i")
(gtk_accel_path "<Actions>/view/view-show-selection" "<Primary>h")
(gtk_accel_path "<Actions>/tools/tools-free-select" "l")
(gtk_accel_path "<Actions>/tools/tools-move" "v")
(gtk_accel_path "<Actions>/view/view-info-window" "F8")
(gtk_accel_path "<Actions>/layers/layers-select-previous" "<Alt>bracketright")
(gtk_accel_path "<Actions>/context/context-brush-hardness-decrease-skip" "braceleft")
(gtk_accel_path "<Actions>/tools/tools-paint-brush-size-decrease" "bracketleft")
(gtk_accel_path "<Actions>/layers/layers-select-next" "<Alt>bracketleft")
(gtk_accel_path "<Actions>/layers/layers-anchor" "<Alt>h")
(gtk_accel_path "<Actions>/view/view-show-menubar" "<Shift>f")
(gtk_accel_path "<Actions>/drawable/drawable-desaturate" "<Primary><Shift>u")
(gtk_accel_path "<Actions>/plug-in/plug-in-c-astretch" "<Primary><Shift><Alt>l")
(gtk_accel_path "<Actions>/tools/tools-scale" "<Primary>t")
(gtk_accel_path "<Actions>/layers/layers-select-bottom" "<Alt>braceleft")
(gtk_accel_path "<Actions>/tools/tools-smudge" "")
(gtk_accel_path "<Actions>/tools/tools-hue-saturation" "<Primary>u")
(gtk_accel_path "<Actions>/edit/edit-fill-pattern" "")
(gtk_accel_path "<Actions>/tools/tools-value-2-decrease" "")
(gtk_accel_path "<Actions>/tools/tools-ellipse-select" "<Shift>m")
(gtk_accel_path "<Actions>/layers/layers-raise-to-top" "<Primary>braceright")
(gtk_accel_path "<Actions>/tools/tools-iscissors" "")
(gtk_accel_path "<Actions>/tools/tools-flip" "f")
(gtk_accel_path "<Actions>/view/view-show-rulers" "<Primary>r")
(gtk_accel_path "<Actions>/windows/windows-display-0006" "<Alt>1")
(gtk_accel_path "<Actions>/windows/windows-display-0009" "<Alt>9")
(gtk_accel_path "<Actions>/windows/windows-display-0008" "<Alt>8")
(gtk_accel_path "<Actions>/windows/windows-display-0007" "<Alt>7")
(gtk_accel_path "<Actions>/dialogs/dialogs-vectors" "F9")
(gtk_accel_path "<Actions>/quick-mask/quick-mask-toggle" "q")
(gtk_accel_path "<Actions>/dialogs/dialogs-palettes" "<Primary><Shift>l")
(gtk_accel_path "<Actions>/layers/layers-mask-add" "<Alt>o")
(gtk_accel_path "<Actions>/plug-in/script_fu_refresh" "<Primary><Shift><Alt>r")
(gtk_accel_path "<Actions>/edit/edit-paste-into" "<Primary><Shift>v")
(gtk_accel_path "<Actions>/tools/tools-fuzzy-select" "w")
(gtk_accel_path "<Actions>/view/view-zoom-out" "<Primary>minus")
(gtk_accel_path "<Actions>/dialogs/dialogs-preferences" "<Primary>k")

# Dump of the GIMP default configuration

(temp-path "\$\{gimp_temp_dir}")
(swap-path "\$\{gimp_cache_dir}")
(num-processors 4)
(tile-cache-size 2012622k)
(use-opencl no)
(interpolation-type cubic)
(default-threshold 15)
(plug-in-path "\$\{gimp_dir}/plug-ins:\$\{gimp_plug_in_dir}/plug-ins")
(module-path "\$\{gimp_dir}/modules:\$\{gimp_plug_in_dir}/modules")
(interpreter-path "\$\{gimp_dir}/interpreters:\$\{gimp_plug_in_dir}/interpreters")
(environ-path "\$\{gimp_dir}/environ:\$\{gimp_plug_in_dir}/environ")
(brush-path "\$\{gimp_dir}/brushes:\$\{gimp_data_dir}/brushes")
(brush-path-writable "\$\{gimp_dir}/brushes")
(dynamics-path "\$\{gimp_dir}/dynamics:\$\{gimp_data_dir}/dynamics")
(dynamics-path-writable "\$\{gimp_dir}/dynamics")
(mypaint-brush-path "/nix/store/wwjbqi2jww5bhw2c60yl3g4r8hynjvap-mypaint-brushes-1.3.0/share/mypaint-data/1.0/brushes:~/.mypaint/brushes")
(mypaint-brush-path-writable "~/.mypaint/brushes")
(pattern-path "\$\{gimp_dir}/patterns:\$\{gimp_data_dir}/patterns")
(pattern-path-writable "\$\{gimp_dir}/patterns")
(palette-path "\$\{gimp_dir}/palettes:\$\{gimp_data_dir}/palettes")
(palette-path-writable "\$\{gimp_dir}/palettes")
(gradient-path "\$\{gimp_dir}/gradients:\$\{gimp_data_dir}/gradients")
(gradient-path-writable "\$\{gimp_dir}/gradients")
(tool-preset-path "\$\{gimp_dir}/tool-presets:\$\{gimp_data_dir}/tool-presets")
(tool-preset-path-writable "\$\{gimp_dir}/tool-presets")
(font-path "\$\{gimp_dir}/fonts:\$\{gimp_data_dir}/fonts")
(default-brush "2. Hardness 050")
(default-dynamics "Dynamics Off")
(default-mypaint-brush "Fixme")
(default-pattern "Pine")
(default-palette "Default")
(default-gradient "FG to BG (RGB)")
(default-tool-preset "Current Options")
(default-font "Sans-serif")
(global-brush yes)
(global-dynamics yes)
(global-pattern yes)
(global-palette yes)
(global-gradient yes)
(global-font yes)
(default-image
    (width 1920)
    (height 1080)
    (unit pixels)
    (xresolution 300.000000)
    (yresolution 300.000000)
    (resolution-unit inches)
    (image-type rgb)
    (precision u8-gamma)
    (color-managed yes)
    (color-profile NULL)
    (fill-type background)
    (comment "Created with GIMP"))
(default-grid
    (style solid)
    (fgcolor (color-rgba 0.000000 0.000000 0.000000 1.000000))
    (bgcolor (color-rgba 1.000000 1.000000 1.000000 1.000000))
    (xspacing 10.000000)
    (yspacing 10.000000)
    (spacing-unit inches)
    (xoffset 0.000000)
    (yoffset 0.000000)
    (offset-unit inches))
(undo-levels 5)
(undo-size 515231232)
(undo-preview-size large)
(plug-in-history-size 10)
(pluginrc-path "\$\{gimp_dir}/pluginrc")
(layer-previews yes)
(group-layer-previews yes)
(layer-preview-size medium)
(thumbnail-size normal)
(thumbnail-filesize-limit 4M)
(color-management
    (mode display)
    (display-profile-from-gdk no)
    (display-rendering-intent relative-colorimetric)
    (display-use-black-point-compensation yes)
    (display-optimize yes)
    (simulation-rendering-intent perceptual)
    (simulation-use-black-point-compensation no)
    (simulation-optimize yes)
    (simulation-gamut-check no)
    (out-of-gamut-color (color-rgb 1.000000 0.000000 1.000000))
    (display-module "CdisplayLcms"))
(save-document-history yes)
(quick-mask-color (color-rgba 1.000000 0.000000 0.000000 0.500000))
(import-promote-float no)
(import-promote-dither yes)
(import-add-alpha no)
(import-raw-plug-in "")
(export-file-type png)
(export-color-profile yes)
(export-metadata-exif yes)
(export-metadata-xmp yes)
(export-metadata-iptc yes)
(debug-policy fatal)
(transparency-size medium-checks)
(transparency-type gray-checks)
(snap-distance 8)
(marching-ants-speed 200)
(resize-windows-on-zoom no)
(resize-windows-on-resize no)
(default-dot-for-dot yes)
(initial-zoom-to-fit yes)
(cursor-mode tool-crosshair)
(cursor-updating yes)
(show-brush-outline yes)
(show-paint-tool-cursor yes)
(image-title-format "%D*%f-%p.%i (%t, %o, %L) %wx%h")
(image-status-format "%n (%m)")
(monitor-xresolution 96.000000)
(monitor-yresolution 96.000000)
(monitor-resolution-from-windowing-system yes)
(navigation-preview-size medium)
(default-view
    (show-menubar yes)
    (show-statusbar yes)
    (show-rulers yes)
    (show-scrollbars yes)
    (show-selection yes)
    (show-layer-boundary yes)
    (show-guides yes)
    (show-grid no)
    (show-sample-points yes)
    (snap-to-guides yes)
    (snap-to-grid no)
    (snap-to-canvas no)
    (snap-to-path no)
    (padding-mode default)
    (padding-color (color-rgb 1.000000 1.000000 1.000000)))
(default-fullscreen-view
    (show-menubar yes)
    (show-statusbar yes)
    (show-rulers yes)
    (show-scrollbars yes)
    (show-selection yes)
    (show-layer-boundary yes)
    (show-guides yes)
    (show-grid no)
    (show-sample-points yes)
    (snap-to-guides yes)
    (snap-to-grid no)
    (snap-to-canvas no)
    (snap-to-path no)
    (padding-mode default)
    (padding-color (color-rgb 1.000000 1.000000 1.000000)))
(activate-on-focus yes)
(space-bar-action pan)
(zoom-quality high)
(use-event-history no)
(move-tool-changes-active no)
(filter-tool-max-recent 10)
(filter-tool-use-last-settings no)
(filter-tool-show-color-options no)
(trust-dirty-flag no)
(save-device-status yes)
(devices-share-tool no)
(save-session-info yes)
(restore-session yes)
(restore-monitor no)
(save-tool-options yes)
(show-tooltips yes)
(tearoff-menus yes)
(can-change-accels no)
(save-accels yes)
(restore-accels yes)
(last-opened-size 10)
(max-new-image-size 128M)
(toolbox-color-area yes)
(toolbox-foo-area no)
(toolbox-image-area no)
(toolbox-wilber yes)
(theme-path "\$\{gimp_dir}/themes:\$\{gimp_data_dir}/themes")
(theme "Dark")
(icon-theme-path "\$\{gimp_dir}/icons:\$\{gimp_data_dir}/icons")
(icon-theme "Symbolic")
(icon-size auto)
(use-help yes)
(show-help-button yes)
(help-locales "")
(help-browser web-browser)
(search-show-unavailable-actions no)
(action-history-size 100)
(user-manual-online no)
(user-manual-online-uri "https://docs.gimp.org/2.10")
(dock-window-hint utility)
(cursor-handedness right)
(playground-npd-tool no)
(playground-seamless-clone-tool no)
(color-profile-policy ask)
(image-convert-profile-intent relative-colorimetric)
(image-convert-profile-black-point-compensation yes)
(image-convert-precision-layer-dither-method none)
(image-convert-precision-text-layer-dither-method none)
(image-convert-precision-channel-dither-method none)
(image-convert-indexed-palette-type generate)
(image-convert-indexed-max-colors 256)
(image-convert-indexed-remove-duplicates yes)
(image-convert-indexed-dither-type none)
(image-convert-indexed-dither-alpha no)
(image-convert-indexed-dither-text-layers no)
(image-resize-fill-type transparent)
(image-resize-layer-set none)
(image-resize-resize-text-layers no)
(layer-new-name "Layer")
(layer-new-mode normal)
(layer-new-blend-space auto)
(layer-new-composite-space auto)
(layer-new-composite-mode auto)
(layer-new-opacity 1.000000)
(layer-new-fill-type transparent)
(layer-resize-fill-type transparent)
(layer-add-mask-type white)
(layer-add-mask-invert no)
(layer-merge-type expand-as-necessary)
(layer-merge-active-group-only yes)
(layer-merge-discard-invisible no)
(channel-new-name "Channel")
(channel-new-color (color-rgba 0.000000 0.000000 0.000000 0.500000))
(path-new-name "Path")
(path-export-active-only yes)
(path-import-merge no)
(path-import-scale no)
(selection-feather-radius 5.000000)
(selection-grow-radius 1.000000)
(selection-shrink-radius 1.000000)
(selection-shrink-edge-lock no)
(selection-border-radius 5.000000)
(selection-border-style smooth)
(selection-border-edge-lock no)
(fill-options
    (style solid)
    (antialias yes)
    (feather no)
    (feather-radius 10.000000))
(stroke-options
    (style solid)
    (antialias yes)
    (feather no)
    (feather-radius 10.000000)
    (method line)
    (width 6.000000)
    (unit pixels)
    (cap-style butt)
    (join-style miter)
    (miter-limit 10.000000)
    (dash-offset 0.000000)
    (dash-info 0)
    (emulate-brush-dynamics no))
(fractalexplorer-path "\$\{gimp_dir}/fractalexplorer:\$\{gimp_data_dir}/fractalexplorer")
(gfig-path "\$\{gimp_dir}/gfig:\$\{gimp_data_dir}/gfig")
(gflare-path "\$\{gimp_dir}/gflare:\$\{gimp_data_dir}/gflare")
(gimpressionist-path "\$\{gimp_dir}/gimpressionist:\$\{gimp_data_dir}/gimpressionist")
(script-fu-path "\$\{gimp_dir}/scripts:\$\{gimp_data_dir}/scripts")

''
